project_id = "nglwgzknqgihlbkdnflu"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.email-oauth-callback]
    verify_jwt = false
  [functions.email-gmail-sync]
    verify_jwt = false
  [functions.send-transactional-email]
    verify_jwt = true
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.handle-email-unsubscribe]
    verify_jwt = false
  [functions.handle-email-suppression]
    verify_jwt = false
  [functions.password-otp-request]
    verify_jwt = false
  [functions.password-otp-verify-and-reset]
    verify_jwt = false
