-- =====================================================================
-- Security fixes from scan results
-- =====================================================================

-- 1) audit_logs: CEO restricted to own tenant; master keeps full access
DROP POLICY IF EXISTS "CEO and Master can view audit logs" ON public.audit_logs;

CREATE POLICY "Master can view all audit logs"
  ON public.audit_logs FOR SELECT
  USING (is_master(auth.uid()));

CREATE POLICY "CEO can view own tenant audit logs"
  ON public.audit_logs FOR SELECT
  USING (
    has_role(auth.uid(), 'ceo'::app_role)
    AND servidor_id = get_user_company_id(auth.uid())
  );

-- 2) profiles INSERT: require target company_id matches caller
DROP POLICY IF EXISTS "Admins can insert profiles in their company" ON public.profiles;

CREATE POLICY "Admins can insert profiles in their company"
  ON public.profiles FOR INSERT
  WITH CHECK (
    is_master(auth.uid())
    OR (
      (has_role(auth.uid(), 'admin'::app_role) OR has_role(auth.uid(), 'ceo'::app_role))
      AND company_id = get_user_company_id(auth.uid())
    )
  );

-- 3) user_roles INSERT: require target user belongs to caller's tenant
DROP POLICY IF EXISTS "Admins can insert roles in their company" ON public.user_roles;

CREATE POLICY "Admins can insert roles in their company"
  ON public.user_roles FOR INSERT
  WITH CHECK (
    is_master(auth.uid())
    OR (
      (has_role(auth.uid(), 'admin'::app_role) OR has_role(auth.uid(), 'ceo'::app_role))
      AND get_profile_company_id(user_id) = get_user_company_id(auth.uid())
    )
  );

-- 4) user_custom_permissions: require target user belongs to caller's tenant
DROP POLICY IF EXISTS "Admin/master can manage user_custom_permissions" ON public.user_custom_permissions;

CREATE POLICY "Admin/master can manage user_custom_permissions"
  ON public.user_custom_permissions FOR ALL
  USING (
    is_master(auth.uid())
    OR (
      (has_role(auth.uid(), 'admin'::app_role) OR has_role(auth.uid(), 'ceo'::app_role))
      AND get_profile_company_id(user_id) = get_user_company_id(auth.uid())
    )
  )
  WITH CHECK (
    is_master(auth.uid())
    OR (
      (has_role(auth.uid(), 'admin'::app_role) OR has_role(auth.uid(), 'ceo'::app_role))
      AND get_profile_company_id(user_id) = get_user_company_id(auth.uid())
    )
  );

-- 5) Tighten always-true policies
DROP POLICY IF EXISTS "Authenticated insert cert logs" ON public.certificate_usage_logs;
CREATE POLICY "Authenticated insert cert logs"
  ON public.certificate_usage_logs FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Service role manages subscriptions" ON public.paddle_subscriptions;
CREATE POLICY "Service role manages subscriptions"
  ON public.paddle_subscriptions FOR ALL
  USING ((auth.jwt() ->> 'role') = 'service_role')
  WITH CHECK ((auth.jwt() ->> 'role') = 'service_role');

DROP POLICY IF EXISTS "Service can insert webhook events" ON public.tenant_asaas_webhook_events;
CREATE POLICY "Service can insert webhook events"
  ON public.tenant_asaas_webhook_events FOR INSERT
  WITH CHECK ((auth.jwt() ->> 'role') = 'service_role');

DROP POLICY IF EXISTS "Service access for tenant sequences" ON public.tenant_contract_sequences;
CREATE POLICY "Service access for tenant sequences"
  ON public.tenant_contract_sequences FOR ALL
  USING ((auth.jwt() ->> 'role') = 'service_role')
  WITH CHECK ((auth.jwt() ->> 'role') = 'service_role');

-- 6) Storage: lock down signatures + contract-pdfs to service role
--    (frontend reads these via signed URLs generated by edge functions)
DROP POLICY IF EXISTS "Authenticated can read signatures" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated can read contract-pdfs" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can update contract PDFs" ON storage.objects;

-- 7) Storage: drop redundant broad write policies on documents bucket
--    Existing 'Admin/operador can upload document files' (INSERT) and
--    'Master can delete document files' (DELETE) take over with proper scoping.
DROP POLICY IF EXISTS "documents_auth_insert" ON storage.objects;
DROP POLICY IF EXISTS "documents_auth_update" ON storage.objects;
DROP POLICY IF EXISTS "documents_auth_delete" ON storage.objects;
DROP POLICY IF EXISTS "documents_auth_select" ON storage.objects;
-- Note: 'Authenticated users can view document files' (broad SELECT) kept
-- intentionally — needed for tenant logos, brand assets, and avatars served
-- across the app. Sensitive docs continue to flow through edge functions.